### ISSUE TITLE
Non-Gifs?

### ISSUE THREAD

**Issue by ghost** [evoL/gif#1]
Started playing with this, and it's well designed ("do one thing well"), thank you!

One problem: it doesn't _need_ to assume that all input is Gif, so why do so? This would be more useful if I could also use it for png, jpg, mp4, mov... etcetera.

This could be a lot simpler than using libmagic or similar, just try to preserve the input file extension?

**Comment by evoL** [comment]
Hey, thanks for asking!

The project name is actually a bit misleading here, because you can use most of the functionality with any file type, if you _really_ want. Personally, I use gifs, jpegs and pngs, but you can put anything inside. Internally the files have a `.gif` extension, because the file format isn't currently used anywhere in code and I wanted to keep this simple. Besides, it's just an (internal) file name.

However, two features support only a limited number of file types:
- importing directories — I assumed that sometimes you can have directories with images mixed with other files, so gif imports just the images. [The recognized file extensions are here.](https://github.com/evoL/gif/blob/master/import.go#L24)
- uploading to Imgur — Well, Imgur doesn't support non-image files, but frankly, I didn't test uploading weird stuff there.

With all that said, I plan to add more image-specific functions in the future, so it's better not to keep your PDFs inside gif 😉

**Comment by ghost** [comment]
Hey,
I'm aware that non-GIFs will import, because I've added mp4s and pngs/jpgs already..but because of their extension being changed to gif, they load with the wrong program, or load incorrectly in the right program.

Keeping the extension the same would fix this problem?

**Comment by evoL** [comment]
This is actually a use case I didn't think about previously! Could you share more details about it?

I'm afraid that just trying to extract the extension wouldn't work in all cases, especially when URLs are involved. Detecting the file type would be more solid and useful in other places in code.

**Comment by evoL** [comment]
Hey, I just wanted to mention that this is a good idea and I want to include this along with some other enhancements in the next release. The issue I created to track the progress is #4.

Thanks for using `gif` and for your feedback; I really appreciate it!
